USE [master]
GO

/****** Object:  Database [OT_ERP_CAN_TRADE]    Script Date: 10/17/2019 8:44:52 PM ******/
CREATE DATABASE [OT_ERP_CAN_TRADE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OT_ERP_CAN_TRADE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014CAN\MSSQL\DATA\OT_ERP_CAN_TRADE.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OT_ERP_CAN_TRADE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014CAN\MSSQL\DATA\OT_ERP_CAN_TRADE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OT_ERP_CAN_TRADE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET ARITHABORT OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET RECOVERY FULL 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET  MULTI_USER 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OT_ERP_CAN_TRADE] SET  READ_WRITE 
GO


